#!/bin/sh

npm run build
kill -9  `ps -ef | grep "webpack-dev-server" | grep 9090 | grep -v grep | awk '{print $2}'`
kill -9  `ps -ef | grep "webpack-dev-server" | grep 9090 | grep -v grep | awk '{print $2}'`

nohup npm run pro &

sleep 5

url='http://localhost:9090/'

wget -qO- $url &> /dev/null
curl -H "Host: stackoverflow.com" -H "Cache-Control: max-age=0" -H "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8" -H "User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.89 Safari/537.36" -H "HTTPS: 1" -H "DNT: 1" -H "Referer: https://www.google.com/" -H "Accept-Language: en-US,en;q=0.8,en-GB;q=0.6,es;q=0.4" -H "If-Modified-Since: Thu, 23 Jul 2015 20:31:28 GMT" --compressed $url > /dev/null 2>&1
